### ISSUE TITLE
Google auth pop up close error.

### ISSUE THREAD

**Issue by Guru89** [deepakaggarwal7/react-social-login#109]
Hi,

Whenever I closed the google pop up without logged in. It shows the following error and if try to log in again it handled by the onLoginFailure function.

Error: [google][auth] Authentication failed

ORIGINAL ERROR: {
  "error": "popup_closed_by_user"
}
    at e.rslError (http://localhost:9006/assets/client.js:10536:79400)
    at http://localhost:9006/assets/client.js:10536:114605
    at h.o0 (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.eBDcOYqPGG4.O/m=auth2/rt=j/sv=1/d=1/ed=1/am=QQE/rs=AGLTcCP5-DOXztU0AEs2tPJq1nqIqSvJ5w/cb=gapi.loaded_0:111:171)
    at xs (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.eBDcOYqPGG4.O/m=auth2/rt=j/sv=1/d=1/ed=1/am=QQE/rs=AGLTcCP5-DOXztU0AEs2tPJq1nqIqSvJ5w/cb=gapi.loaded_0:114:335)
    at Wq (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.eBDcOYqPGG4.O/m=auth2/rt=j/sv=1/d=1/ed=1/am=QQE/rs=AGLTcCP5-DOXztU0AEs2tPJq1nqIqSvJ5w/cb=gapi.loaded_0:114:186)
    at _.C.uea (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.eBDcOYqPGG4.O/m=auth2/rt=j/sv=1/d=1/ed=1/am=QQE/rs=AGLTcCP5-DOXztU0AEs2tPJq1nqIqSvJ5w/cb=gapi.loaded_0:114:52)
    at Ap (https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.eBDcOYqPGG4.O/m=auth2/rt=j/sv=1/d=1/ed=1/am=QQE/rs=AGLTcCP5-DOXztU0AEs2tPJq1nqIqSvJ5w/cb=gapi.loaded_0:107:284)
From previous event:
    at o.d [as _captureStackTrace] (http://localhost:9006/assets/client.js:10536:11063)
    at o._resolveFromExecutor (http://localhost:9006/assets/client.js:10536:46312)
    at new o (http://localhost:9006/assets/client.js:10536:38640)
    at Object.c [as login] (http://localhost:9006/assets/client.js:10536:114459)
    at n.<anonymous> (http://localhost:9006/assets/client.js:10536:93396)
    at commitCallbacks (http://localhost:9006/assets/vendor.js:13955:110)
    at commitLifeCycles (http://localhost:9006/assets/vendor.js:14015:329)
    at c (http://localhost:9006/assets/vendor.js:14026:208)
    at k (http://localhost:9006/assets/vendor.js:14029:408)
    at p (http://localhost:9006/assets/vendor.js:14030:367)
    at batchedUpdates (http://localhost:9006/assets/vendor.js:14036:267)
    at qb (http://localhost:9006/assets/vendor.js:13887:344)
    at ob (http://localhost:9006/assets/vendor.js:13887:278)
    at Object.batchedUpdates (http://localhost:9006/assets/vendor.js:13888:85)
    at dispatchEvent (http://localhost:9006/assets/vendor.js:13891:162)

**Comment by deepakaggarwal7** [comment]
I know it was reported long back. Still, I want your help to understand it.

1. user clicks Login with Google => popup opens
2. user closes the popup window => console shows error
3. user clicks login again => 1. repeats
This seems logical behaviour. What's the preferred outcome?
