### ISSUE TITLE
Not working on SSR

### ISSUE THREAD

**Issue by azappa** [deepakaggarwal7/react-social-login#71]
On a SSR project, using the code in README I got this error in development (terminal output):
```bash
ReferenceError: document is not defined
    at Object.<anonymous> (/Users/ale/Repos/XYZ/node_modules/react-social-login/dist/social-login.js:1:77909)
    at e (/Users/ale/Repos/XYZ/node_modules/react-social-login/dist/social-login.js:1:419)
    at Object.e._id (/Users/ale/Repos/XYZ/node_modules/react-social-login/dist/social-login.js:1:101300)
    at e (/Users/ale/Repos/XYZ/node_modules/react-social-login/dist/social-login.js:1:419)
    at Object.<anonymous> (/Users/ale/Repos/XYZ/node_modules/react-social-login/dist/social-login.js:1:86775)
    at e (/Users/ale/Repos/XYZ/node_modules/react-social-login/dist/social-login.js:1:419)
    at Object.<anonymous> (/Users/ale/Repos/XYZ/node_modules/react-social-login/dist/social-login.js:1:96348)
    at e (/Users/ale/Repos/XYZ/node_modules/react-social-login/dist/social-login.js:1:419)
    at Object.t.__esModule.default (/Users/ale/Repos/XYZ/node_modules/react-social-login/dist/social-login.js:1:90868)
    at e (/Users/ale/Repos/XYZ/node_modules/react-social-login/dist/social-login.js:1:419)
    at Object.t.__esModule.default (/Users/ale/Repos/XYZ/node_modules/react-social-login/dist/social-login.js:1:89721)
    at e (/Users/ale/Repos/XYZ/node_modules/react-social-login/dist/social-login.js:1:419)
    at /Users/ale/Repos/XYZ/node_modules/react-social-login/dist/social-login.js:1:776
    at /Users/ale/Repos/XYZ/node_modules/react-social-login/dist/social-login.js:1:785
    at n.(anonymous function).i (/Users/ale/Repos/XYZ/node_modules/react-social-login/dist/social-login.js:1:84)
    at Object.<anonymous> (/Users/ale/Repos/XYZ/node_modules/react-social-login/dist/social-login.js:1:295)
```

Could you provide a demo code with SSR support in examples?

**Comment by nicolas-goudry** [comment]
Hi @azappa, thanks for reporting this issue.

It’s a bug from rsl, I will patch it as soon as I can.

**Comment by jkettmann** [comment]
@nicolas-goudry Can you make a release? Thanks

**Comment by nicolas-goudry** [comment]
@jkettmann I’ll make a release today 🎊

**Comment by nicolas-goudry** [comment]
@jkettmann Just released it :+1:
